[template]
src = "10-frontend_%port%.cfg.tmpl"
dest = "/opt/haproxy/etc/conf.d/10-frontend_%port%.cfg"
owner = "haproxy"
mode = "0644"
keys = [
  "/stacks",
]

reload_cmd = "/opt/haproxy/bin/haproxy-service.sh start"
